### ISSUE TITLE
Sample Java Code is outdated and does not work with Android. 

### ISSUE THREAD

**Issue by anikseu** [WMSPanel/paywall-code-samples-wmsauth#2]
Sample Java Code uses Apache Common Codecs 1.5 which is quite old and does not work in Android environment. 

So to make it work with Android, I used java.util.Base64 instead of Common Codec. and changed the few lines like this example: 
` 

        byte[] ascii_to_hash = to_hash.getBytes("UTF-8");

        MessageDigest md = MessageDigest.getInstance("MD5");

        String base64hash = Base64.getEncoder().encodeToString(md.digest(ascii_to_hash));

        String urlsignature = "server_time=" + today + "&hash_value=" + base64hash + "&validminutes=" + validminutes;

        String base64urlsignature = Base64.getEncoder().encodeToString(urlsignature.getBytes("UTF-8"));`

**Comment by alexpokotilo** [comment]
It's not a good idea to sign links on a mobile device in general because you need to send signature key to every mobile clients. Instead you need to sign links on your back-end and send already signed links to authorized mobile clients. This way only authorized clients get signed links but you don't send signed key to your mobile clients. Just imagine somebody get your Android app code, de-compile it and log/grab your signature key.
This is why we don't much care about mobile platforms as it's better to sign links on your back-end
